config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do 
  	resources :comments
  	member do
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
  end

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable

	belongs_to :user

	has_many :comments

	#for paperclip gem
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		#find post
		@post = Post.find(params[:post_id])

		#create comments using comment content
		@comment = Comment.create(params[:comment].permit(:content))

		#assign comment to signed in user
		@comment.user_id = current_user.id

		#comments post to commented post
		@comment.post_id = @post.id

		if @comment.save
			redirect_to @post
		else
			render 'new'
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote] 
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@post = Post.all.order("created_at DESC")
	end


	def show
		@comments = Comment.where(post_id: @post )
	end


	def new
		@post = current_user.posts.build
	end


	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		
	end


	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end			
	end


	def destroy
		@post = Post.find(params[:id])

		if @post.present?
			@post.destroy
		end

		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user
		redirect_to :back		
	end


	private

		def find_post
			@post = Post.find(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :link, :description, :image)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :content, label: "Reply to Cribble" %>

	<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<%= f.input :image, class: "form-control" %>
	<%= f.input :title, class: "form-control" %>
	<%= f.input :link, class: "form-control" %>
	<%= f.input :description, class: "form-control" %>

	<%= f.button :submit %>
<% end %>			

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-7 col-lg-offset-3">

			<h1>Edit your Cribble Post</h1>

			<%= render 'form' %>

		</div>
	</div>
</div>

app/views/posts/index.html.erb
<h1>Home Page</h1>

<% @post.each do |post| %>
	<%= link_to(image_tag post.image.url(:small)) %>
	<h3><%= link_to post.title, post %></h3>
	<p><%= pluralize(post.comments.count, "Comment") %> </p>
	<p><%= post.get_upvotes.size %> Likes</p>
<% end %>

<%= link_to "Add new Cribble", new_post_path(@post) %>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-7 col-lg-offset-3">

			<h1>New Cribble Post</h1>

			<%= render 'form' %>

		</div>
	</div>
</div>

app/views/posts/show.html.erb
<%= image_tag @post.image.url(:medium) %>
<h1><%= @post.title %></h1>
<p><%= @post.link %></p>
<p><%= @post.description %></p>
<p><%= @post.user.name %></p>

<p><%= pluralize(@post.get_upvotes.size, "Likes") %></p>
<p><%= pluralize(@post.get_downvotes.size, "Dislikes") %></p>

<%= link_to "Upvote", like_post_path(@post), method: :get %>
<%= link_to "Downvote", dislike_post_path(@post), method: :get %>

<div id="comment_container">
	<h2 class="comment_count">
		<%= pluralize(@post.comments.count, "Comment") %>
	</h2>
	<% @comments.each do |comment| %>
		<div class="comment">
			<p class="username">
				<%= comment.user.name %>
			</p>
			<p class="content">
				<%= comment.content %>
			</p>
		</div>
	<% end %>
</div>

<%= render 'comments/form' %>

<%= link_to "Home", root_path %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Destroy", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>